# Generated by Django 6.0.4 on 2026-05-31 21:59

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=core.fields.UpperCaseCharField(max_length=200, verbose_name='Назва книги'),
        ),
    ]
