# Generated by Django 6.0.4 on 2026-06-05 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_book_author_rel_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author_rel'], name='books_book_author_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre'], name='books_book_genre_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book'], name='books_review_book_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='books_review_rating_idx'),
        ),
    ]
