"""
Django settings for django_my_site project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import sys
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import pymongo

# Побудова шляхів всередині проєкту
BASE_DIR = Path(__file__).resolve().parent.parent

# Автоматичне створення папки для логів, якщо її немає
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Завантаження змінних оточення з .env
load_dotenv(BASE_DIR / '.env')

# --- НАСТРОЙКИ БЕЗОПАСНОСТИ ДЛЯ ПРОДАКШЕНА ---
DEBUG = os.getenv('DEBUG', 'False') == 'True'

SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY and not DEBUG:
    raise ValueError("Критическая ошибка безопасности: SECRET_KEY не задан в .env!")

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',

    # Ваші локальні додатки (Застосунки)
    'main',
    'board',
    'core',
    'user',
    'books.apps.LibraryConfig',
    'todo',
    'shop',

    # Сторонні пакети
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'axes',
    'django_extensions',
]

MIDDLEWARE = [
    # 1. Centralized Error Handling (Must be first!)
    'user.middleware.ErrorHandlingMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'user.middleware.AuditAccessMiddleware',

    'axes.middleware.AxesMiddleware',
    'core.middleware.CustomHeaderMiddleware',
    'core.middleware.RequestMetricsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'books.middleware.AnonymousBooksCacheMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'django_my_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_site_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_my_site.wsgi.application'

# Database configuration (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'my_site_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'mypassword'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5433'),
        'ATOMIC_REQUESTS': True,
    }
}

# КРИТИЧНО НЕОБХІДНО: Налаштування кешу для лімітів @ratelimit та пакету Axes
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'TIMEOUT': 300, # Кэш по умолчанию живет 5 минут
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'uk-ua'  # Українська мова для системних повідомлень та форм
TIME_ZONE = 'Europe/Kyiv'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MONGO_CLIENT = pymongo.MongoClient("mongodb://localhost:27017/")
# Створюємо або підключаємо базу даних 'library_nosql'
MONGO_DB = MONGO_CLIENT["library_nosql"]
# Колекція (аналог таблиці) для книг із гнучкими атрибутами
MONGO_BOOKS_COLLECTION = MONGO_DB["books_attributes"]

# Налаштування для django-allauth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesStandaloneBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

LOGIN_REDIRECT_URL = '/profile/'  # Куди перенаправляти після входу
LOGOUT_REDIRECT_URL = '/profile/login/'  # Куди перенаправляти після виходу

# Django REST Framework & Simple JWT
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Library Management REST API',
    'DESCRIPTION': 'API для управління бібліотекою книг з підтримкою CRUD, фільтрації, пагінації та JWT-авторизації.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{'BearerAuth': []}],
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'APPEND_COMPONENTS': {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}

# Определяем, запущены ли тесты в данный момент
IS_TESTING = 'test' in sys.argv

# --- ОПТИМИЗИРОВАННЫЕ НАСТРОЙКИ БЕЗОПАСНОСТИ ---
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
AXES_IP_WHITELIST = ['127.0.0.1']

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = "sessionid_secure"
SESSION_COOKIE_AGE = 1209600
CSRF_USE_SESSIONS = False

# Настройки SSL/HSTS отключаются при DEBUG или во время ТЕСТОВ
if DEBUG or IS_TESTING:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_RELOAD = False
else:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_RELOAD = True

# ДОМЕНЫ ДЛЯ CSRF (Замените 'yourusername' на ваш реальный логин PythonAnywhere)
CSRF_TRUSTED_ORIGINS = [
    "https://*.pythonanywhere.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000"
]

SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Об'єднана та виправлена система логування
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/error.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'analytics_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/server_activity.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'core_analytics': {
            'handlers': ['analytics_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'user.middleware': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

# --- НАСТРОЙКИ CELERY ---
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# --- НАСТРОЙКИ ОТПРАВКИ EMAIL ---
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '://gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_USER', 'your_email@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD', 'your_app_password')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

if 'test' in sys.argv:
    # Перемикаємо кєш на оперативну пам'ять (якщо не було додано раніше)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake-cache',
        }
    }

    # Видаляємо дебаг-панель із списку Middleware, щоб вона не перехоплювала запити
    if 'debug_toolbar.middleware.DebugToolbarMiddleware' in MIDDLEWARE:
        MIDDLEWARE = [m for m in MIDDLEWARE if m != 'debug_toolbar.middleware.DebugToolbarMiddleware']

    # Видаляємо дебаг-панель із встановлених додатків
    if 'debug_toolbar' in INSTALLED_APPS:
        INSTALLED_APPS = [app for app in INSTALLED_APPS if app != 'debug_toolbar']
