# Generated by Django 6.0.4 on 2026-05-31 21:59

import board.models
import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=core.fields.UpperCaseCharField(default='#0D6EFD', max_length=7, verbose_name='Колір категорії (HEX)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[board.models.validate_positive_price]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=core.fields.UpperCaseCharField(max_length=150, verbose_name='Заголовок оголошення'),
        ),
    ]
